### ISSUE TITLE
Possible imposter instance!

### ISSUE THREAD

**Issue by mineyannik** [thechunknetwork/RedisBungee#16]
Hello.

I restart one of my BungeeCord instances and get this error.

```
03:03:58 [SEVERE] [RedisBungee] You have launched a possible imposter BungeeCord instance. Another instance is already running.
03:03:58 [SEVERE] [RedisBungee] For data consistency reasons, RedisBungee will now disable itself.
03:03:58 [SEVERE] [RedisBungee] If this instance is coming up from a crash, create a file in your RedisBungee plugins directory with the name 'restarted_from_crash.txt' and RedisBungee will not perform this check.
03:03:58 [WARNING] Exception encountered when loading plugin: RedisBungee
java.lang.RuntimeException: Possible imposter instance!
	at com.imaginarycode.minecraft.redisbungee.RedisBungee.loadConfig(RedisBungee.java:425)
	at com.imaginarycode.minecraft.redisbungee.RedisBungee.onEnable(RedisBungee.java:228)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:220)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:250)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```
Also RedisBungee isn't working after that. I have to restart my BungeeCord instance a second time.

**Comment by minecrafter** [comment]
Please make sure you shut down BungeeCord cleanly and make sure the server-id is not in use anywhere else

**Comment by minecrafter** [comment]
Also note:

`03:03:58 [SEVERE] [RedisBungee] If this instance is coming up from a crash, create a file in your RedisBungee plugins directory with the name 'restarted_from_crash.txt' and RedisBungee will not perform this check.`
